server:
  port: 80


spring:
  application:
    name: cloud-order-service #微服务名称
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}1