server:
  port: 7001
#Server 可以不用自己注册自己
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 不搭建集群 单机 指向自己
      #defaultZone: http://eureka7002.com:7002/eureka/ # 搭建集群 集群是指向其他eureka 互相注册，相互守望
    server:
      enable-self-preservation: false # 关闭自我保护机制 保证不可用服务及时清除
      eviction-interval-timer-in-ms: 1000   #单位是毫秒