server:
  port: 8004


spring:
  application:
    name: cloud-payment-service #微服务名称
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&useUnicode=true
      username: root
      password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.1.115:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描Mapper位置
  type-aliases-package: com.xzq.springcloud.entities  #所有entity别名所在包
#  zipkin:
#    base-url: http://localhost:9411
#    sleuth:
#      sampler:
#        probability: 1